### ISSUE TITLE
Remove support for Fusillade

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-cli#22]
In `test/integration/auth/test_auth_api.py` we create an auth client that points to a Fusillade instance. 

In discussion around #16 ([link to discussion](https://github.com/DataBiosphere/data-store-cli/pull/16#discussion_r373735692)) @amarjandu suggested removing support for Fusillade.

This ticket is to remove support for Fusillade from the data store CLI tool.

**Comment by melainalegaspi** [comment]
Closing, taking a different approach to this issue
