### ISSUE TITLE
Make OIDC Layer more flexible in dbio-cli

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-cli#43]
Implement changes mentioned in DataBiosphere/data-store#80 in the CLI tool

**Comment by kozbo** [comment]
Closely related to databiosphere/data-store#91

**Comment by chmreid** [comment]
Update with some information on our strategy:
- we will be treating the data store CLI and the data store API as two separate Auth0 applications
- to do authentication with Auth0, the data store CLI needs to have an application secret
    - previously, this was provided by the data store API at the `/internal/application_secrets` endpoint
    - now, we will add a very simple API gateway that serves up this application secret JSON to the newly-created DataBiosphere/data-store-auth repo (which contains only infrastructure)
    - the data store CLI will use this application secret to authenticate users with Auth0
- the data store CLI will require a machine-to-machine application token (https://auth0.com/machine-to-machine)

**Comment by chmreid** [comment]
In order for us to authenticate/create JWTs using Auth0 and create a machine-to-machine token, we need to be able to get application secrets

To get application secrets we need DataBiosphere/data-store-auth#4 (add the application secret to a new auth API endpoint) to be implemented

**Comment by chmreid** [comment]
<s>Pull request DataBiosphere/data-store-auth#3 will implement the API endpoint mentioned above</s>

The idea above is being scrapped

**Comment by chmreid** [comment]
Current approach: keep the `/internal/application_secrets` API endpoint in the data store.

CLI tool will be redirected to appropriate login endpoint using data store's OIDC layer and swagger.

Resulting JWT will contain token-level email/group claims added by us, plus (if DSS using Auth0 backend) a custom Auth0 token claim. This will contain the Auth0 AuthZ plugin's token (which has groups/roles/permissions info).

**Comment by chmreid** [comment]
This is being held up by DataBiosphere/data-store#145 (enable auth0 backend), which was closed and marked complete, as well as supporting PRs/work to fix tests broken by enabling Auth0 (DataBiosphere/data-store#154, DataBiosphere/data-store#155, DataBiosphere/data-store#156). Once those are complete we can test out the security flow in the dbio cli tool and get it working.
